### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by solidsnack** [posix4e/jsoncdc#17]
It should have a cool name like: _Dungeons & Dragons_, _Pikachu_, _My Little Pony: Enterprise_ or _Beyond Big Data_.

One option is `rpg` for Reactive PostGres.
- [x] Come up with some names.
- [x] Choose from names.

**Comment by solidsnack** [comment]
Working name is `jsoncdc`.

**Comment by solidsnack** [comment]
- [ ] Rename repo.

**Comment by posix4e** [comment]
I'm thinking i like rpg
