### ISSUE TITLE
Create a c bridge (sys portion) to the postgresql logical decoding libraries

### ISSUE THREAD

**Issue by posix4e** [posix4e/jsoncdc#2]
This might have to be a ffi, but I wonder if we even need that. Perhaps we can just handle it at the rpc level. Of course this will create issues between postgresql versioning.

**Comment by posix4e** [comment]
@solidsnack What do we think?

**Comment by solidsnack** [comment]
How do we handle it at the RPC layer? Like, we write a parser for the protocol?

**Comment by posix4e** [comment]
Looking at the streaming replication protocol, actually reimplementing the whole protocol and format in rust seems hard. Eventually it might be nice to do, but for now, we probably want to just great an ffi bridge for pgxs.

So the easy way for now is just to bridge from the existing postgresql library 
http://doxygen.postgresql.org/test__decoding_8c_source.html

for example 
https://github.com/leptonix/decoding-json/blob/master/decoding_json.c

are the minimum libraries we will probably need to ffi bridge

static void pg_decode_startup(LogicalDecodingContext\* ctx, OutputPluginOptions\* opt, bool is_init);
static void pg_decode_shutdown(LogicalDecodingContext\* ctx);
static void pg_decode_begin_txn(LogicalDecodingContext\* ctx, ReorderBufferTXN\* txn);
static void pg_output_begin(LogicalDecodingContext\* ctx, DecodingJsonData\* data, ReorderBufferTXN\* txn, bool last_write);
static void pg_decode_commit_txn(LogicalDecodingContext\* ctx, ReorderBufferTXN\* txn, XLogRecPtr commit_lsn);
static void pg_decode_change(LogicalDecodingContext\* ctx, ReorderBufferTXN\* txn, Relation rel, ReorderBufferChange\* change);

With the curl ffi changes I made, we ended up having two repos, with git submodules of each other
https://github.com/carllerche/curl-rust

Now I know what you are going to say, doesn't this mean we have to have unsafe rust code! The answer is yes but at least we can reduce the surface area.

**Comment by posix4e** [comment]
I created https://github.com/posix4e/elephantpump/issues/6 to track the rust portion of this code. I am repurposing this issue to target the c bridge (-sys) crate for accessing postgresql logical replication

**Comment by solidsnack** [comment]
So I am a little out of my depth here with regards to C extensions and Rust. There are three barriers to my understanding:
- How do we use a macro like `PG_MODULE_MAGIC`?
- How do we import and then re-export C things? For example, in [`curl-sys` in `lib.rs`][curlsys] the functions `curl_easy_*` seem only to be exported, not defined; so it looks like we are getting them from the library.
- Do we need C headers? In `curl-sys` there does not appear to be any reference to `curl.h`.

[curlsys] https://github.com/carllerche/curl-rust/blob/master/curl-sys/lib.rs#L470

**Comment by solidsnack** [comment]
Okay, I think I get it. `extern` is not `export`, so that was my first problem. And the reason we can do

``` rust
extern {
  ...
  pub fn <c-func>(<param>: <rust-type>, ...) -> <rust-type>;
  ...
}
```

is because all the Rust types in question are `[#repr(C)]` or are aliases for stuff from `libc`.

**Comment by posix4e** [comment]
Nice!

**Comment by posix4e** [comment]
The structs are super nested in this postgresql interface. Seems like that's 99% of the work is getting  LogicalDecodingContext ffid

**Comment by solidsnack** [comment]
What is `ffid`?

**Comment by posix4e** [comment]
ffi-ed hooked up to ffi
