### ISSUE TITLE
Write schema information only once per transaction

### ISSUE THREAD

**Issue by solidsnack** [posix4e/jsoncdc#38]
Most of the time, we can expect a log stream to involve a few operations altogether on one table, as in [base.sql](https://github.com/posix4e/jsoncdc/blob/eaf732977aae4aa5255f0c2aeb343ba0832e26be/test/sql/base.sql). In that situation, the table schema will be output once, followed by data rows (as in [base.out](https://github.com/posix4e/jsoncdc/blob/eaf732977aae4aa5255f0c2aeb343ba0832e26be/test/expected/base.out)).

However, a transaction could also do a few operations by going and back and forth between a few different tables, as in [tricky.sql](https://github.com/posix4e/jsoncdc/blob/eaf732977aae4aa5255f0c2aeb343ba0832e26be/test/sql/tricky.sql). Without grouping these changes, we need to repeat the table information so that we know which table the change applies to, as in [tricky.out](https://github.com/posix4e/jsoncdc/blob/eaf732977aae4aa5255f0c2aeb343ba0832e26be/test/expected/tricky.out).

Grouping changes might use a fair amount of space. Repeating the table name -- but not the schema -- would be simpler, involving storing only the fact that for this transaction, we printed the schema already. Both would imply dynamic data structures, however.

**Comment by posix4e** [comment]
Perhaps we should have an example processor?

**Comment by solidsnack** [comment]
Writing schema once per transaction is not actually strictly correct, since it could change from one write to another within the same transaction; but I am not sure what to do to capture the DDL in a way that properly reflects this. I suppose...one looks at the schema info as one pulls each row? And if it changes, send it?

**Comment by posix4e** [comment]
This makes sense to me

**Comment by ruimarinho** [comment]
I'm not sure if this was spawned due to my mention of writing the schema per each row. I think I induced you in confusion as by `schema` I actually mention a postgres schema name (e.g. "public.foo") and not the actual table structure. 

I don't think that outputting the whole DDL per each transaction is ideal though, so perhaps put that behind a flag?

**Comment by solidsnack** [comment]
@ruimarinho This is actually a somewhat older issue, and relates to the present practice of writing the `{ "table": ..., "schema": ...` record and then the `{ "insert"|"update"|"delete": ...` records after them.

The issue is that if we switch back and forth between tables during a transaction, we of course need to write the table information again. Later, I realized that if the schema for the table changes during a transaction, it also needs to be written again.

The motivation for this is restoring from the JSON archive, say to a point in time in the past. You do want to know, what the table looked like at that time.

**Comment by posix4e** [comment]
Certainly this is no longer a blocker?
