### ISSUE TITLE
Filter system tables

### ISSUE THREAD

**Issue by jmealo** [posix4e/jsoncdc#49]
When you refresh a materialized view you get a lot of noise. Some people may want to stream `pg_temp` tables; but a good majority may not.

I think table filters are important if you can keep them performant.

In the interest of not using expensive pattern matching; it may be worthwhile to have a boolean option to suppress system tables and just check the first three characters of the string.

Sure, you could name a table `pg_shoot_myself_in_the_foot`, but that's on you, right ;-)?

**Comment by posix4e** [comment]
Very cool
On Fri, Apr 8, 2016 at 12:56 PM Jeffrey <notifications@github.com> wrote:

> When you refresh a materialized view you get a lot of noise. Some people
> may want to stream pg_temp tables; but a good majority may not.
>
> I think table filters are important if you can keep them performant.
>
> In the interest of not using expensive pattern matching; it may be
> worthwhile to have a boolean option to suppress system tables and just
> check the first three characters of the string.
>
> Sure, you could name a table pg_shoot_myself_in_the_foot, but that's on
> you, right ;-)?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/posix4e/jsoncdc/issues/49>
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by solidsnack** [comment]
@jmealo For materialized views, do you think there is a type level filter we can apply? I will look into this soon but any insights you have will speed things along.

I can imagine filters like this:
- Name based: `a.*` (schema), `a*` (table name), `a*.b*` (both), following Postgres quoting rules.
- Type based: is it a view, is it a temp table, &c

A Rust implementation would actually be fairly straightforward. The configuration will vary in size but we can hopefully get this information from Rust to feed to `palloc`. I do wonder where/how to pass the configuration, though. `pg_create_logical_replication_slot()` does not provide a way to pass options.

**Comment by solidsnack** [comment]
Hmm, options are passed with `pg_logical_slot_get_changes()`.

**Comment by posix4e** [comment]
@solidsnack tell me more. What options are passed?

**Comment by posix4e** [comment]
Can we do this on installation. Can we filter when the logical is installed?

**Comment by ruimarinho** [comment]
I like the filtering proposed by @solidsnack. Whitelisting and/or blacklisting would be very interesting.
To my knowledge, options are only available on the startup callback, not during the creation phase. Could `filter_by_origin_cb`/`FilterOrigin` be of any help?

**Comment by jmealo** [comment]
Any updates on this? I plan to replace decoding_json with jsoncdc in [JarvusInnovations/Lapidus](https://github.com/JarvusInnovations/lapidus) and would like to support this if possible.

**Comment by solidsnack** [comment]
We are going to have a meeting next week to talk about it.

**Comment by jmealo** [comment]
Where did we land on this? Does this still make sense with pub/sub` in core?

This could be a good exercise in passing settings into the output plugin from PG.

**Random thought:** Can we get to the `GUC` from an output plugin? Would that be insane?

@ruimarinho: The filter origin callback is for preventing replication loops, the documentation/purpose for its use are much clearer now that pglogical has landed.

**Comment by jmealo** [comment]
**This issue was fixed upstream in PostgreSQL 10.3:**
https://github.com/postgres/postgres/commit/b9bf23abb0e9a63ecc5f4b68a8229146291270e5

> "Prevent logical replication from trying to replicate changes for unpublishable relations, such as materialized views and the "information_schema" tables"
https://www.postgresql.org/about/news/1834/

> Prevent logical replication from trying to ship changes for unpublishable relations (Peter Eisentraut)
> 
> A publication marked FOR ALL TABLES would incorrectly ship changes in materialized views and information_schema tables, which are supposed to be omitted from the change stream.
https://www.postgresql.org/docs/current/static/release-10-3.html#id-1.11.6.5.5

Since it's considered a bug, I guess we shouldn't handle it in JSONCDC.

**Comment by bascarsija** [comment]
does this mean that users will be stuck with the bug until they can upgrade to Postgres 10.3?

note that such an upgrade (including acceptance testing) may be a massive undertaking (or nonstarter) for some users.

**Comment by jmealo** [comment]
@bascarsija: this project has moved to: https://github.com/instructure/jsoncdc
If we want to further discuss/re-open this issue it should be done there.
