### ISSUE TITLE
Why isn't the primary key always sent?

### ISSUE THREAD

**Issue by jmealo** [posix4e/jsoncdc#61]
## See @solidsnack's answer below

I'm trying to convert Lapidus to use jsoncdc and am wondering why the primary key isn't always sent. Is this intentional?

I'm not sure if it's convention, but when I was doing my initial research it seemed like it was common to include this. Here's an example on how one might retrieve it:
https://github.com/leptonix/decoding-json/blob/master/decoding_json.c#L233

**Comment by solidsnack** [comment]
Hi Jeff,

It should be sent for updates and deletes, actually; but it does depend on one's Postgres configuration (whether `REPLICA IDENTITY` is set or not).

https://github.com/posix4e/jsoncdc/blob/master/src/lib.rs#L116

This would seem to be exact same logic as you link to above.

With the default setting of `REPLICA IDENTITY`, Postgres only sets `oldtuple` if the primary key changed -- for deletes it is always sent, but for updates it might be skipped. This can be seen in the tests; like in:

https://github.com/posix4e/jsoncdc/blob/master/test/expected/base.out

Do you observe something different with `decoding_json`?

**Comment by jmealo** [comment]
@solidsnack: Nope, this is perfect. I read the PostgreSQL documentation for fun and the release notes and I completely missed this! Thanks for the info.
