### ISSUE TITLE
TOASTed values not always available for reading

### ISSUE THREAD

**Issue by solidsnack** [posix4e/jsoncdc#63]
From [IRC](irc://chat.freenode.net/postgresql):

> RhodiumToad:
> so the bottom line is that if a value didn't change in an update, you can't rely on being able to retrieve it

**Comment by ruimarinho** [comment]
Exactly - so TOASTed values are not always dumped to the WAL and that means we can't blindly [copy the tuple as a datum](https://github.com/posix4e/jsoncdc/blob/master/src/lib.rs#L131), as some attributes may contain an indirect pointer to the data which could be no longer accessible. This is particularly important for `REPLICA IDENTITY DEFAULT`.

We would need to replace jsoncdc's implementation to use [heap_deform_tuple](https://github.com/postgres/postgres/blob/3aff33aa687e47d52f453892498b30ac98a296af/src/backend/access/heap/tuptoaster.c#L1212) and test if the column's _varlena_ is still detoastable. 

There is a good test case on [toast.out](https://github.com/postgres/postgres/blob/3aff33aa687e47d52f453892498b30ac98a296af/contrib/test_decoding/expected/toast.out) for [test_decoding.c](https://github.com/postgres/postgres/blob/3aff33aa687e47d52f453892498b30ac98a296af/contrib/test_decoding/test_decoding.c).  Note that `test_decoding.c` is not using `heap_deform_tuple`, which is more efficient as per RhodiumToad's comment on IRC.

So, in case that the indirect pointer references external data ONDISK, then we would need to take one of three decisions from my point of view: set the column as `null`, omit the column or include an array of columns which remained unchanged. I think the most correct approach would be omitting the column, as `null` could represent an actual value, and the unchanged column array could be uninteresting, as we would not be able to access the actual value anyway. 

Regarding `REPLICA IDENTITY FULL`, we know that the `old` value will always have the detoasted value, but the `new` value may not still be readable if it remained unchanged. In this case, we could merge the `old` value with the `new` one.

Note that when TOASTed columns are changed, we will receive the new value detoasted. This is just an _optimization_ (or a caveat, depending on the perspective) of postgres when dealing with WAL records.

Did this sound confusing at all?

**Comment by solidsnack** [comment]
It doesn't sound confusing at all.

I agree with you about column omission. I think merging with `REPLICA IDENTITY FULL` will work and that would be the right implementation although I am a little fuzzy on how to handle `NULL` in the `old` row. Is there some way to detect that we are in `REPLICA IDENTITY FULL` mode?

**Comment by solidsnack** [comment]
@ruimarinho Back to working on this.

**Comment by posix4e** [comment]
Can we close?
