### ISSUE TITLE
Ensure handling of non-existent columns in old tuple versions

### ISSUE THREAD

**Issue by ruimarinho** [posix4e/jsoncdc#64]
Noticed [this commit](https://github.com/postgres/postgres/commit/d47a1136e441cebe7ae7fe72d70eb8ce278d5cd6) which might affect the current implementation:

> test_decoding used fastgetattr() to extract column values. That's wrong when decoding updates and deletes if a table's replica identity is set to FULL and new columns have been added since the old version of the tuple was created. Due to the lack of a crosscheck with the datum's natts values an invalid value will be output, leading to errors or worse.

**Comment by solidsnack** [comment]
The present implementation using `row_to_json` handles this because `row_to_json` calls `composite_to_json` and `composite_to_json` [checks `attisdropped`](http://doxygen.postgresql.org/json_8c_source.html#l01713).
