### ISSUE TITLE
Port pg_recvlogical to Rust (Logical Decoding Client)

### ISSUE THREAD

**Issue by jmealo** [posix4e/jsoncdc#71]
Porting `pg_recvlogical` to Rust will allow us to output line delimited JSON for error output and connection status. Currently wrapping `pg_recvlogical` in a higher-level API requires locale/fork specific string parsing (https://github.com/JarvusInnovations/lapidus/blob/master/src/postgresql.js#L186).

Deliverables:
1. Command line equivalent of `pg_recv_logical`

Future features:
* Use neon to wrap `pg_recv_logical` to expose an event emitter in Node for PostgreSQL (I would like to try to do this!)

MySQL parity:
1. Command line equivalent of `pg_recv_logical` using `libbinlogevents`

**Comment by posix4e** [comment]
This seems like something beyond the scope of this project, but until we have a better place for it, let's let it stick here so i can ponder. I wonder if a library alone would be useful

**Comment by jmealo** [comment]
There are now Go and Node.js examples that do not wrap pg_recvlogical so this isn't a show stopper for someone following in our footsteps (embracing logical decoding). **I would really like a single binary client that doesn't require the entire PG source tree to build.** That being said, myself or anyone else who wants to take this on has plenty of simple examples if they get stuck. The protocol really couldn't be any simpler.
