### ISSUE TITLE
pg_logical_emit_message support

### ISSUE THREAD

**Issue by jmealo** [posix4e/jsoncdc#75]
As of 9.6, `pg_logical_emit_message` is available. It will allow us to send arbitrary messages to the WAL from triggers and such. I've suggested that the postgraphql community check you guys out, I believe that this feature will eliminate any benefit to using `NOTIFY`/`LISTEN` over logical decoding (other than configuration complexity and environmental constraints).

**Comment by posix4e** [comment]
Neat!

**Comment by jmealo** [comment]
@posix4e: @solidsnack: What can I do to help get this ready before PG 10 is released? I think I have got it mostly complete in: #76
